### ISSUE TITLE
Error sending request

### ISSUE THREAD

**Issue by anandhakumarnataraj** [ingeint/idempierewsc-java#1]
Hi,

We have tried the web-service connector through an eclipse and as well as Android studio and it has been setup correctly. And then changed the credentials and URL then run the application with emulator and i got the below mentioned error.

Error sending request

While we checking an issue with logcat and find the below error.
Caused by: java.io.FileNotFoundException: http://{ipaddress}/ADInterface/services/ModelADService

**Comment by sauljabin** [comment]
Hi, I'm sorry for the delay, did you solve the problem?
